[build]
  command = "NETLIFY_SKIP_SECRET_DETECTION=true npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888