// Common electrical materials for autocomplete
export const COMMON_ELECTRICAL_MATERIALS = [
  // Receptacles & Outlets
  '15A Duplex Receptacle',
  '20A Duplex Receptacle',
  '15A GFCI Receptacle',
  '20A GFCI Receptacle',
  '15A AFCI Receptacle',
  '20A AFCI Receptacle',
  '30A Receptacle',
  '50A Receptacle',
  'USB Outlet',
  'USB-C Outlet',
  'USB-A/C Combo Outlet',
  'Weatherproof Outlet Cover',
  'In-Use Weatherproof Cover',
  'Dryer Receptacle 30A',
  'Range Receptacle 50A',
  'Twist Lock Receptacle 20A',
  'Twist Lock Receptacle 30A',
  'Hospital Grade Receptacle',
  'Tamper Resistant Receptacle',
  'Isolated Ground Receptacle',
  
  // Switches
  'Single-Pole Switch',
  'Three-Way Switch',
  'Four-Way Switch',
  'Double Pole Switch',
  'Dimmer Switch',
  '3-Way Dimmer Switch',
  'Smart Switch',
  'Smart Dimmer',
  'Timer Switch',
  'Motion Sensor Switch',
  'Occupancy Sensor',
  'Vacancy Sensor',
  'Photocell Switch',
  'Pilot Light Switch',
  'Lighted Switch',
  'Rocker Switch',
  'Decora Switch',
  
  // NM-B Wire (Romex)
  '14/2 NM-B Wire (Romex)',
  '12/2 NM-B Wire (Romex)',
  '10/2 NM-B Wire (Romex)',
  '8/2 NM-B Wire (Romex)',
  '6/2 NM-B Wire (Romex)',
  '14/3 NM-B Wire (Romex)',
  '12/3 NM-B Wire (Romex)',
  '10/3 NM-B Wire (Romex)',
  '8/3 NM-B Wire (Romex)',
  '6/3 NM-B Wire (Romex)',
  '4/3 NM-B Wire (Romex)',
  '3/3 NM-B Wire (Romex)',
  '2/3 NM-B Wire (Romex)',
  
  // MC Cable (Metal Clad)
  '14/2 MC Cable',
  '12/2 MC Cable',
  '10/2 MC Cable',
  '8/2 MC Cable',
  '6/2 MC Cable',
  '14/3 MC Cable',
  '12/3 MC Cable',
  '10/3 MC Cable',
  '8/3 MC Cable',
  '6/3 MC Cable',
  '14/4 MC Cable',
  '12/4 MC Cable',
  '10/4 MC Cable',
  
  // AC Cable (BX)
  '14/2 AC Cable (BX)',
  '12/2 AC Cable (BX)',
  '14/3 AC Cable (BX)',
  '12/3 AC Cable (BX)',
  
  // SO Cord (Portable Power Cable)
  '12/2 SO Cord',
  '12/3 SO Cord',
  '12/4 SO Cord',
  '10/2 SO Cord',
  '10/3 SO Cord',
  '10/4 SO Cord',
  '8/3 SO Cord',
  '8/4 SO Cord',
  '6/3 SO Cord',
  '6/4 SO Cord',
  
  // SOOW Cord (Oil Resistant)
  '12/3 SOOW Cord',
  '10/3 SOOW Cord',
  '8/3 SOOW Cord',
  '6/3 SOOW Cord',
  
  // THHN/THWN Wire (Single Conductor)
  'THHN Wire #14',
  'THHN Wire #12',
  'THHN Wire #10',
  'THHN Wire #8',
  'THHN Wire #6',
  'THHN Wire #4',
  'THHN Wire #3',
  'THHN Wire #2',
  'THHN Wire #1',
  'THHN Wire #1/0',
  'THHN Wire #2/0',
  'THHN Wire #3/0',
  'THHN Wire #4/0',
  'THHN Wire 250 MCM',
  'THHN Wire 300 MCM',
  'THHN Wire 350 MCM',
  'THHN Wire 400 MCM',
  'THHN Wire 500 MCM',
  
  // Ground Wire
  '#14 Bare Ground Wire',
  '#12 Bare Ground Wire',
  '#10 Bare Ground Wire',
  '#8 Bare Ground Wire',
  '#6 Bare Ground Wire',
  '#4 Bare Ground Wire',
  '#2 Bare Ground Wire',
  '#14 Green Ground Wire',
  '#12 Green Ground Wire',
  '#10 Green Ground Wire',
  '#8 Green Ground Wire',
  '#6 Green Ground Wire',
  
  // EMT Conduit
  '1/2" EMT Conduit (10ft)',
  '3/4" EMT Conduit (10ft)',
  '1" EMT Conduit (10ft)',
  '1-1/4" EMT Conduit (10ft)',
  '1-1/2" EMT Conduit (10ft)',
  '2" EMT Conduit (10ft)',
  '2-1/2" EMT Conduit (10ft)',
  '3" EMT Conduit (10ft)',
  '4" EMT Conduit (10ft)',
  
  // EMT Connectors
  '1/2" EMT Connector',
  '3/4" EMT Connector',
  '1" EMT Connector',
  '1-1/4" EMT Connector',
  '1-1/2" EMT Connector',
  '2" EMT Connector',
  '2-1/2" EMT Connector',
  '3" EMT Connector',
  '4" EMT Connector',
  
  // EMT Couplings
  '1/2" EMT Coupling',
  '3/4" EMT Coupling',
  '1" EMT Coupling',
  '1-1/4" EMT Coupling',
  '1-1/2" EMT Coupling',
  '2" EMT Coupling',
  '2-1/2" EMT Coupling',
  '3" EMT Coupling',
  '4" EMT Coupling',
  
  // EMT Compression Connectors
  '1/2" EMT Compression Connector',
  '3/4" EMT Compression Connector',
  '1" EMT Compression Connector',
  '1-1/4" EMT Compression Connector',
  '1-1/2" EMT Compression Connector',
  '2" EMT Compression Connector',
  
  // EMT Set Screw Connectors
  '1/2" EMT Set Screw Connector',
  '3/4" EMT Set Screw Connector',
  '1" EMT Set Screw Connector',
  '1-1/4" EMT Set Screw Connector',
  '1-1/2" EMT Set Screw Connector',
  '2" EMT Set Screw Connector',
  
  // Rigid Conduit
  '1/2" Rigid Conduit (10ft)',
  '3/4" Rigid Conduit (10ft)',
  '1" Rigid Conduit (10ft)',
  '1-1/4" Rigid Conduit (10ft)',
  '1-1/2" Rigid Conduit (10ft)',
  '2" Rigid Conduit (10ft)',
  '2-1/2" Rigid Conduit (10ft)',
  '3" Rigid Conduit (10ft)',
  '4" Rigid Conduit (10ft)',
  
  // IMC Conduit
  '1/2" IMC Conduit (10ft)',
  '3/4" IMC Conduit (10ft)',
  '1" IMC Conduit (10ft)',
  '1-1/4" IMC Conduit (10ft)',
  '1-1/2" IMC Conduit (10ft)',
  '2" IMC Conduit (10ft)',
  
  // PVC Conduit (Schedule 40)
  '1/2" PVC Conduit (10ft)',
  '3/4" PVC Conduit (10ft)',
  '1" PVC Conduit (10ft)',
  '1-1/4" PVC Conduit (10ft)',
  '1-1/2" PVC Conduit (10ft)',
  '2" PVC Conduit (10ft)',
  '2-1/2" PVC Conduit (10ft)',
  '3" PVC Conduit (10ft)',
  '4" PVC Conduit (10ft)',
  '5" PVC Conduit (10ft)',
  '6" PVC Conduit (10ft)',
  
  // PVC Conduit (Schedule 80)
  '1/2" PVC Schedule 80 Conduit',
  '3/4" PVC Schedule 80 Conduit',
  '1" PVC Schedule 80 Conduit',
  '1-1/4" PVC Schedule 80 Conduit',
  '1-1/2" PVC Schedule 80 Conduit',
  '2" PVC Schedule 80 Conduit',
  
  // PVC Elbows
  '1/2" PVC Elbow 90°',
  '3/4" PVC Elbow 90°',
  '1" PVC Elbow 90°',
  '1-1/4" PVC Elbow 90°',
  '1-1/2" PVC Elbow 90°',
  '2" PVC Elbow 90°',
  '2-1/2" PVC Elbow 90°',
  '3" PVC Elbow 90°',
  '4" PVC Elbow 90°',
  '1/2" PVC Elbow 45°',
  '3/4" PVC Elbow 45°',
  '1" PVC Elbow 45°',
  
  // PVC Couplings
  '1/2" PVC Coupling',
  '3/4" PVC Coupling',
  '1" PVC Coupling',
  '1-1/4" PVC Coupling',
  '1-1/2" PVC Coupling',
  '2" PVC Coupling',
  '2-1/2" PVC Coupling',
  '3" PVC Coupling',
  '4" PVC Coupling',
  '5" PVC Coupling',
  '6" PVC Coupling',
  
  // PVC Male Adapters
  '1/2" PVC Male Adapter',
  '3/4" PVC Male Adapter',
  '1" PVC Male Adapter',
  '1-1/4" PVC Male Adapter',
  '1-1/2" PVC Male Adapter',
  '2" PVC Male Adapter',
  '3" PVC Male Adapter',
  '4" PVC Male Adapter',
  
  // PVC Female Adapters
  '1/2" PVC Female Adapter',
  '3/4" PVC Female Adapter',
  '1" PVC Female Adapter',
  '1-1/4" PVC Female Adapter',
  '1-1/2" PVC Female Adapter',
  '2" PVC Female Adapter',
  '3" PVC Female Adapter',
  '4" PVC Female Adapter',
  
  // Bushings (Insulated)
  '1/2" Insulated Bushing',
  '3/4" Insulated Bushing',
  '1" Insulated Bushing',
  '1-1/4" Insulated Bushing',
  '1-1/2" Insulated Bushing',
  '2" Insulated Bushing',
  '2-1/2" Insulated Bushing',
  '3" Insulated Bushing',
  '4" Insulated Bushing',
  
  // Plastic Bushings
  '1/2" Plastic Bushing',
  '3/4" Plastic Bushing',
  '1" Plastic Bushing',
  '1-1/4" Plastic Bushing',
  '1-1/2" Plastic Bushing',
  '2" Plastic Bushing',
  
  // Grounding Bushings
  '1/2" Grounding Bushing',
  '3/4" Grounding Bushing',
  '1" Grounding Bushing',
  '1-1/4" Grounding Bushing',
  '1-1/2" Grounding Bushing',
  '2" Grounding Bushing',
  '2-1/2" Grounding Bushing',
  '3" Grounding Bushing',
  '4" Grounding Bushing',
  
  // Locknuts
  '1/2" Locknut',
  '3/4" Locknut',
  '1" Locknut',
  '1-1/4" Locknut',
  '1-1/2" Locknut',
  '2" Locknut',
  '2-1/2" Locknut',
  '3" Locknut',
  '4" Locknut',
  
  // Chase Nipples
  '1/2" Chase Nipple',
  '3/4" Chase Nipple',
  '1" Chase Nipple',
  '1-1/4" Chase Nipple',
  '1-1/2" Chase Nipple',
  '2" Chase Nipple',
  
  // Grommets
  '1/2" Snap-In Grommet',
  '3/4" Snap-In Grommet',
  '1" Snap-In Grommet',
  '1-1/4" Snap-In Grommet',
  '1-1/2" Snap-In Grommet',
  '2" Snap-In Grommet',
  'Rubber Grommet 1/2"',
  'Rubber Grommet 3/4"',
  'Rubber Grommet 1"',
  
  // Boxes - Single Gang
  'Single Gang Old Work Box',
  'Single Gang New Work Box',
  'Single Gang Metal Box',
  'Single Gang Weatherproof Box',
  'Single Gang Deep Box',
  'Single Gang Box w/ Clamps',
  'Single Gang Box w/ Bracket',
  
  // Boxes - Double Gang
  'Double Gang Old Work Box',
  'Double Gang New Work Box',
  'Double Gang Metal Box',
  'Double Gang Deep Box',
  'Double Gang Box w/ Clamps',
  
  // Boxes - Triple/Quad Gang
  'Triple Gang Old Work Box',
  'Triple Gang New Work Box',
  'Quad Gang Old Work Box',
  'Quad Gang New Work Box',
  
  // Junction Boxes - Square
  '4" Square Box 1-1/2" Deep',
  '4" Square Box 2-1/8" Deep',
  '4-11/16" Square Box 1-1/2" Deep',
  '4-11/16" Square Box 2-1/8" Deep',
  '4" Square Box Cover Blank',
  '4" Square Box Cover w/ Knockout',
  '4-11/16" Square Box Cover',
  
  // Junction Boxes - Octagon
  '4" Octagon Box 1-1/2" Deep',
  '4" Octagon Box 2-1/8" Deep',
  '4" Octagon Box Cover',
  
  // Junction Boxes - Round
  '3" Round Old Work Box',
  '4" Round Old Work Box',
  'Round Pancake Box',
  
  // Junction Boxes - Weatherproof
  'Weatherproof Box 1-Gang',
  'Weatherproof Box 2-Gang',
  'FSB Box (Weatherproof)',
  'FS Box (Weatherproof)',
  'FD Box (Weatherproof)',
  
  // Pull Boxes
  '6x6x4 Junction Box',
  '8x8x4 Junction Box',
  '10x10x4 Junction Box',
  '12x12x4 Junction Box',
  '12x12x6 Junction Box',
  '16x16x6 Junction Box',
  '18x18x6 Junction Box',
  '24x24x6 Junction Box',
  
  // Handy Boxes
  'Handy Box',
  'Handy Box w/ Clamps',
  'Handy Box Cover',
  
  // Breakers - Standard
  '15A Single Pole Breaker',
  '20A Single Pole Breaker',
  '30A Single Pole Breaker',
  '40A Single Pole Breaker',
  '50A Single Pole Breaker',
  '60A Single Pole Breaker',
  '70A Single Pole Breaker',
  '80A Single Pole Breaker',
  '90A Single Pole Breaker',
  '100A Single Pole Breaker',
  
  // Breakers - Double Pole
  '15A Double Pole Breaker',
  '20A Double Pole Breaker',
  '30A Double Pole Breaker',
  '40A Double Pole Breaker',
  '50A Double Pole Breaker',
  '60A Double Pole Breaker',
  '70A Double Pole Breaker',
  '80A Double Pole Breaker',
  '100A Double Pole Breaker',
  
  // GFCI Breakers
  '15A GFCI Breaker',
  '20A GFCI Breaker',
  '30A GFCI Breaker',
  '40A GFCI Breaker',
  '50A GFCI Breaker',
  '60A GFCI Breaker',
  
  // AFCI Breakers
  '15A AFCI Breaker',
  '20A AFCI Breaker',
  
  // AFCI/GFCI Combo Breakers
  '15A AFCI/GFCI Breaker',
  '20A AFCI/GFCI Breaker',
  
  // Tandem Breakers
  '15/15A Tandem Breaker',
  '20/20A Tandem Breaker',
  '15/20A Tandem Breaker',
  
  // Panels
  '100A Load Center',
  '125A Load Center',
  '150A Load Center',
  '200A Load Center',
  '400A Load Center',
  '100A Sub Panel',
  '125A Sub Panel',
  '200A Sub Panel',
  'Panel Cover',
  'Panel Door',
  'Panel Trim',
  
  // Lighting Fixtures
  'LED Bulb A19',
  'LED Bulb BR30',
  'LED Bulb PAR38',
  'LED Bulb GU10',
  'LED Bulb Candelabra',
  'LED Recessed Light 4"',
  'LED Recessed Light 6"',
  'Can Light Housing',
  'Can Light Trim',
  'Pendant Light',
  'Chandelier',
  'Vanity Light Bar',
  'Bathroom Vanity Light',
  'Ceiling Fan 52"',
  'Ceiling Fan w/ Light',
  'Ceiling Fan Downrod',
  'Under Cabinet LED Light',
  'Track Lighting Kit',
  'Wall Sconce',
  'Outdoor Wall Light',
  'Outdoor Post Light',
  'Motion Sensor Flood Light',
  'LED Strip Light (16ft)',
  'Exit Sign',
  'Emergency Light',
  
  // Smoke & CO Detectors
  'Smoke Detector Hardwired',
  'Smoke Detector Battery',
  'Smoke/CO Combo Detector',
  'Carbon Monoxide Detector',
  'Heat Detector',
  
  // Doorbell & Chimes
  'Doorbell Transformer',
  'Doorbell Button',
  'Doorbell Chime',
  'Video Doorbell',
  'Ring Doorbell',
  
  // Thermostats
  'Thermostat Programmable',
  'Smart Thermostat',
  'Nest Thermostat',
  'Ecobee Thermostat',
  'Line Voltage Thermostat',
  
  // Wire Connectors
  'Wire Nuts - Yellow',
  'Wire Nuts - Red',
  'Wire Nuts - Blue',
  'Wire Nuts - Orange',
  'Wire Nuts - Gray',
  'Push-In Wire Connectors',
  'Lever Wire Connectors',
  'Wire Splice Connectors',
  
  // Fasteners & Hardware
  'Wire Staples',
  'Romex Staples',
  'Cable Ties 8"',
  'Cable Ties 14"',
  'Zip Ties',
  'Conduit Straps 1/2"',
  'Conduit Straps 3/4"',
  'Conduit Straps 1"',
  'One-Hole Straps 1/2"',
  'One-Hole Straps 3/4"',
  'Two-Hole Straps',
  'J-Hooks',
  'Bridle Rings',
  'Beam Clamps',
  'All-Thread Rod 1/4"',
  'All-Thread Rod 3/8"',
  'All-Thread Rod 1/2"',
  'Threaded Rod Coupling',
  'Hex Nuts',
  'Lock Washers',
  'Flat Washers',
  
  // Tape & Sealants
  'Electrical Tape',
  'Duct Seal',
  'Fire Caulk',
  'Silicone Caulk',
  'PVC Cement',
  'PVC Primer',
  'Anti-Oxidant Compound',
  
  // Grounding
  'Ground Rod 8ft',
  'Ground Rod 10ft',
  'Ground Rod Clamp',
  'Ground Lug',
  'Ground Bar',
  'Grounding Pigtail',
  'Bonding Jumper',
  'Bonding Bushing',
  
  // Disconnect & Safety Switches
  '30A Disconnect',
  '60A Disconnect',
  '100A Disconnect',
  '200A Disconnect',
  'AC Disconnect',
  'Fused Disconnect',
  'Non-Fused Disconnect',
  'Safety Switch 30A',
  'Safety Switch 60A',
  'Safety Switch 100A',
  
  // HVAC Related
  'Whip 6ft',
  'Whip 10ft',
  'Liquid Tight Connector 3/8"',
  'Liquid Tight Connector 1/2"',
  'Liquid Tight Connector 3/4"',
  'Liquid Tight Conduit 3/8"',
  'Liquid Tight Conduit 1/2"',
  'Liquid Tight Conduit 3/4"',
  
  // Data/Low Voltage
  'Cat6 Cable',
  'Cat5e Cable',
  'Cat6a Cable',
  'Coax Cable RG6',
  'Coax Cable RG59',
  'Keystone Jack Cat6',
  'Keystone Jack Cat5e',
  'Coax Keystone Jack',
  'Wall Plate 1-Gang',
  'Wall Plate 2-Gang',
  'Wall Plate 3-Gang',
  'Blank Insert',
  'Ethernet Jack',
  'Phone Jack RJ11',
  'HDMI Wall Plate',
  'Speaker Wire 14/2',
  'Speaker Wire 16/2',
  'Low Voltage Bracket',
  'Low Voltage Ring',
  'Cable Reel',
  
  // Weatherproofing
  'Weatherproof Cover In-Use',
  'Weatherproof Cover Vertical',
  'Weatherproof Cover Horizontal',
  'Outdoor Box Gasket',
  'LB Conduit Body',
  'LL Conduit Body',
  'LR Conduit Body',
  'T Conduit Body',
  'C Conduit Body',
  'E Conduit Body',
  
  // Misc Electrical
  'Fuse Adapter',
  'Fuse 15A',
  'Fuse 20A',
  'Fuse 30A',
  'Terminal Block',
  'DIN Rail',
  'Butt Splice Connector',
  'Ring Terminal',
  'Spade Terminal',
  'Heat Shrink Tubing',
  'Wire Loom',
  'Split Loom',
  'Fish Tape',
  'Pull String',
  'Meter Socket',
  'Meter Base',
  'CT Cabinet',
];

// Function to get materials as objects (for Firebase)
export const getCommonMaterialsAsObjects = () => {
  return COMMON_ELECTRICAL_MATERIALS.map(name => ({
    name,
    cost: 0, // No default price
    usageCount: 0,
    isCommon: true // Flag to identify pre-populated items
  }));
};